### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'author')

### ISSUE THREAD

**Issue by thomasbnt** [mrrobotdotapp/classic-discord-webhook#8]
## How to produce

Run the Action workflow without data (like push a new version or tag).

~https://github.com/Mist3r-Robot/classic-discord-webhook/actions/runs/2609387600/jobs/4036716089~

> Received 0/0 commits...
> Preparing Webhook...
> Constructing Embed...
> undefined
> Error: Cannot read properties of undefined (reading 'author')

**Comment by Ladam0203** [comment]
Hey, the logs for the action workflow expired :/

**Comment by thomasbnt** [comment]
> Hey, the logs for the action workflow expired :/

Oh 😐

It is when a version has been created that the action starts and displays the error.
You should simply check if the author of the commit is present, if not, then you do nothing.

Or you send the message but with different information. (Maybe we could set this in the workflow, if we activate it or not)
Traduit avec DeepL https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by thomasbnt** [comment]
> Hey, the logs for the action workflow expired :/

Oh 😐

It is when a version has been created that the action starts and displays the error.
You should simply check if the author of the commit is present, if not, then you do nothing.

Or you send the message but with different information. (Maybe we could set this in the workflow, if we activate it or not)

**Comment by thomasbnt** [comment]
Hello @ajmeese7 ! I think this issue come from `dist/index.js`. I edited `src/index.js` to check if commits is here or not, and also changing some lines like  https://github.com/mrrobotdotapp/classic-discord-webhook/blob/main/src/index.js#L19
```javascript
  console.log(`Received ${size} commits...`)
``` 
But stil have "Received 1/1 commits..." output ([See on actions](https://github.com/mrrobotdotapp/classic-discord-webhook/actions/runs/8592341716/job/23542210425#step:3:211))

How I can update the script?

**Comment by ajmeese7** [comment]
@thomasbnt do you still require any assistance here or is this issue good to be closed?

**Comment by thomasbnt** [comment]
> @thomasbnt do you still require any assistance here or is this issue good to be closed?

Hello @ajmeese7! Sorry for useless ping, and seems worked! I can close this issue. 

@Ladam0203 this issue was resolved with the new version of the Action. No need to change the endpoint. 


Good day!
